# application.yml 主配置文件
# 项目相关配置
breze:
  # 标题
  title: 清枫Breze一体化服务平台
  # 项目名
  name: Breze
  # 项目描述
  description: Breze权限管理系统接口文档
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 版权归属
  copyrightName: 青枫网络工作室
  # Swagger文档启停,生产环境建议关闭
  swaggerEnabled: true

spring:
  #  配置激活文件
  profiles:
    active: dev
    # 对配置文件进行分组激活，届时可根据不同环境进行修改
    group:
      "dev": datasource,redis,rabbitmq,mail,timedtask,private
      "prod": datasource,redis,rabbitmq,mail,timedtask,private
      "test": datasource,redis,rabbitmq,mail,timedtask,private
  # 限制文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:application-log.yml
  # 设置日志分组
  group:
    common: com.breze.common
    controller: com.breze.controller
    service: com.breze.service,com.breze.impl
    mapper: com.breze.mapper.**
  # 根据分组设定日志级别
  level:
    # 项目整体日志级别
    root: info
    # 项目分组各模块日志级别
    common: info
    controller: debug
    service: debug
    mapper: debug